# Generated by Django 2.2.3 on 2019-11-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willflyy', '0002_auto_20191021_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='cr_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='msg',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(null=True, upload_to='profiles'),
        ),
    ]
